### ISSUE TITLE
realpath not on Mac OS

### ISSUE THREAD

**Issue by tsaijet** [mzpqnxow/pybuild23#3]
On MacOS Mojave v10.14.1 9Darwin Kernel Version 18.2.0)
make
Makefile:76: *** "No realpath in PATH.  Stop.

realpath doesn't exist on MacOS. Suggestion is to replace with readlink or create bash script to simulate realpath ... (https://stackoverflow.com/questions/3572030/bash-script-absolute-path-with-os-x)

**Comment by mzpqnxow** [comment]
wow what a toy os! Maybe you send me a pull request @tsaijet?
